---
- name: ENSURE TENANT EXISTS
  aci_tenant:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    state: "present"
    validate_certs: False
    tenant: "{{ tenant }}"
    description: "Tenant Created Using Ansible"
  