---
- name: Add a new ANP to Tenant
  aci_ap:
   host: "{{ apic }}"
   username: "{{ username }}"
   password: "{{ password }}"
   validate_certs: no
   tenant: "{{ item.tenant }}"
   ap: "{{ item.name }}"
   description: "{{ item.description }}"
   state: present
  with_items: "{{ anps }}"
