---
- name: associate a bd to an existing l3out
  aci_bd_to_l3out:
    host: "{{ apic }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    tenant: "{{ item.tenant }}"
    bd: "{{ item.name }}"
    l3out: "{{ item.l3out }}"
  with_items: "{{ bds }}"
  when: "'WEB-TIER' in item.name"
