---
- name: Deploy infrastructure
  hosts: apic
  connection: local
  gather_facts: false
  vars_files:
    - variables.yml


  roles:
    - aci_tenant
    - aci_anp
    - aci_bd
    - aci_bd_subnet
    - aci_bd_to_l3out
    - aci_epg
    #- aci_epg_to_domain
    #- aci_epg_to_contract
