---
- name: Add a new tenant
  aci_tenant:
    host: "{{ apic }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: false
    tenant: "{{item.name}}"
    description: "{{item.description}}"
    state: present
  with_items: "{{ tenants }}"
