FROM centos

RUN yum check-update; \
    yum install -y gcc libffi-devel python3 epel-release; \
    yum install -y python3-pip; \
    yum clean all

RUN pip3 install --upgrade pip; \
    pip3 install ansible;

RUN yum update ansible

RUN ansible-galaxy collection install cisco.aci    

