---
# tasks file for aci_physical_add_fabric_node
- name: Add fabric node
  aci_fabric_node:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    state: "present"
    validate_certs: False
    serial: "{{ item.serial }}"
    node_id: "{{ item.node_id }}"
    switch: "{{ item.switch }}"
    state: present
  with_items: "{{ NODES }}"
